const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const products = [
  // Semen & Bahan Perekat (5 products)
  {
    name: "Semen Gresik Portland",
    description:
      "Semen berkualitas tinggi untuk konstruksi umum, cocok untuk pengecoran dan pasangan bata",
    sku: "SEM-GRS-001",
    price: 65000,
    categorySlug: "semen-bahan-perekat",
    unit: "sak",
    weight: 50,
    stock: 150,
    minStock: 30,
    isFeatured: true,
  },
  {
    name: "Semen Tiga Roda",
    description:
      "Semen premium dengan kekuatan tinggi untuk berbagai aplikasi konstruksi",
    sku: "SEM-TR-002",
    price: 63000,
    categorySlug: "semen-bahan-perekat",
    unit: "sak",
    weight: 50,
    stock: 120,
    minStock: 25,
  },
  {
    name: "Mortar Utama MU-400",
    description: "Mortar instan untuk pemasangan batako dan plesteran dinding",
    sku: "MRT-UTM-003",
    price: 45000,
    salePrice: 42000,
    categorySlug: "semen-bahan-perekat",
    unit: "sak",
    weight: 40,
    stock: 80,
    minStock: 20,
    isFeatured: true,
  },
  {
    name: "Lem Kayu Rajawali Super",
    description: "Lem kayu berkualitas tinggi untuk berbagai jenis kayu",
    sku: "LEM-RJW-004",
    price: 25000,
    categorySlug: "lem-perekat",
    unit: "botol",
    weight: 1,
    stock: 200,
    minStock: 50,
  },
  {
    name: "Lem Keramik Sika CeraGlue",
    description: "Lem keramik premium untuk pemasangan keramik dan granit",
    sku: "LEM-SKA-005",
    price: 85000,
    categorySlug: "lem-perekat",
    unit: "sak",
    weight: 25,
    stock: 60,
    minStock: 15,
  },

  // Pasir & Agregat (3 products)
  {
    name: "Pasir Bangka Halus",
    description: "Pasir halus berkualitas untuk plesteran dan acian dinding",
    sku: "PSR-BNK-006",
    price: 450000,
    categorySlug: "pasir-agregat",
    unit: "m3",
    weight: 1400,
    stock: 25,
    minStock: 5,
  },
  {
    name: "Pasir Cor Kasar",
    description: "Pasir kasar untuk pengecoran beton struktural",
    sku: "PSR-COR-007",
    price: 420000,
    categorySlug: "pasir-agregat",
    unit: "m3",
    weight: 1500,
    stock: 30,
    minStock: 8,
  },
  {
    name: "Kerikil Split 2/3",
    description: "Kerikil pecah untuk campuran beton berkekuatan tinggi",
    sku: "KRK-SPL-008",
    price: 380000,
    categorySlug: "pasir-agregat",
    unit: "m3",
    weight: 1600,
    stock: 20,
    minStock: 5,
  },

  // Bata & Batako (4 products)
  {
    name: "Bata Merah Press Jumbo",
    description:
      "Bata merah berkualitas tinggi hasil pressing untuk dinding kokoh",
    sku: "BAT-MRH-009",
    price: 1200,
    categorySlug: "bata-batako",
    unit: "pcs",
    weight: 3.5,
    stock: 5000,
    minStock: 1000,
    isFeatured: true,
  },
  {
    name: "Batako Press Abu-abu",
    description: "Batako press kualitas premium untuk dinding partisi",
    sku: "BTK-ABU-010",
    price: 3500,
    categorySlug: "bata-batako",
    unit: "pcs",
    weight: 8,
    stock: 2000,
    minStock: 400,
  },
  {
    name: "Hebel Blesscon 60x20x10",
    description: "Bata ringan AAC untuk konstruksi cepat dan ringan",
    sku: "HBL-BLS-011",
    price: 9500,
    salePrice: 9000,
    categorySlug: "bata-batako",
    unit: "pcs",
    weight: 5,
    stock: 800,
    minStock: 150,
    isFeatured: true,
  },
  {
    name: "Bata Ekspos Natural",
    description: "Bata ekspos untuk tampilan dinding natural dan artistik",
    sku: "BAT-EKS-012",
    price: 2500,
    categorySlug: "bata-batako",
    unit: "pcs",
    weight: 4,
    stock: 1500,
    minStock: 300,
  },

  // Cat & Finishing (5 products)
  {
    name: "Cat Tembok Avitex Interior White",
    description: "Cat tembok interior berkualitas tinggi warna putih bersih",
    sku: "CAT-AVT-013",
    price: 285000,
    salePrice: 270000,
    categorySlug: "cat-finishing",
    unit: "pail",
    weight: 25,
    stock: 100,
    minStock: 20,
    isFeatured: true,
  },
  {
    name: "Cat Kayu Propan Wood Stain",
    description: "Cat kayu transparan untuk finishing kayu natural",
    sku: "CAT-PRN-014",
    price: 95000,
    categorySlug: "cat-finishing",
    unit: "kaleng",
    weight: 3,
    stock: 150,
    minStock: 30,
  },
  {
    name: "Cat Besi Nippon Paint Red Oxide",
    description: "Cat anti karat untuk material besi dan logam",
    sku: "CAT-NPN-015",
    price: 110000,
    categorySlug: "cat-finishing",
    unit: "kaleng",
    weight: 4,
    stock: 80,
    minStock: 15,
  },
  {
    name: "Cat Dulux Weathershield Exterior",
    description: "Cat eksterior tahan cuaca untuk dinding luar",
    sku: "CAT-DLX-016",
    price: 450000,
    categorySlug: "cat-finishing",
    unit: "pail",
    weight: 20,
    stock: 60,
    minStock: 12,
  },
  {
    name: "Plamir Tembok Avian Putih",
    description: "Plamir untuk meratakan permukaan dinding sebelum pengecatan",
    sku: "PLM-AVN-017",
    price: 65000,
    categorySlug: "cat-finishing",
    unit: "pail",
    weight: 10,
    stock: 120,
    minStock: 25,
  },

  // Keramik & Granit (4 products)
  {
    name: "Keramik Lantai Roman 40x40 dBellagio",
    description: "Keramik lantai motif natural stone untuk ruang tamu",
    sku: "KRM-RMN-018",
    price: 85000,
    salePrice: 78000,
    categorySlug: "keramik-granit",
    unit: "dus",
    weight: 20,
    stock: 150,
    minStock: 30,
    isFeatured: true,
  },
  {
    name: "Keramik Dinding Asia Tile 25x40",
    description: "Keramik dinding glossy untuk kamar mandi",
    sku: "KRM-AST-019",
    price: 65000,
    categorySlug: "keramik-granit",
    unit: "dus",
    weight: 18,
    stock: 200,
    minStock: 40,
  },
  {
    name: "Granit Tile Platinum 60x60 Polished",
    description: "Granit tile premium dengan finishing poles mengkilap",
    sku: "GRN-PLT-020",
    price: 185000,
    categorySlug: "keramik-granit",
    unit: "dus",
    weight: 30,
    stock: 80,
    minStock: 15,
    isFeatured: true,
  },
  {
    name: "Keramik Kamar Mandi Arwana 30x30",
    description: "Keramik anti slip untuk lantai kamar mandi",
    sku: "KRM-ARW-021",
    price: 55000,
    categorySlug: "keramik-granit",
    unit: "dus",
    weight: 16,
    stock: 180,
    minStock: 35,
  },

  // Besi & Baja (4 products)
  {
    name: "Besi Beton Ulir 10mm Full SNI",
    description: "Besi beton ulir diameter 10mm untuk struktur bangunan",
    sku: "BSI-BTN-022",
    price: 95000,
    categorySlug: "besi-baja",
    unit: "batang",
    weight: 6,
    stock: 500,
    minStock: 100,
    isFeatured: true,
  },
  {
    name: "Besi Hollow 4x4 Tebal 1.2mm",
    description: "Besi hollow untuk rangka pintu, jendela, dan kanopi",
    sku: "BSI-HLW-023",
    price: 125000,
    categorySlug: "besi-baja",
    unit: "batang",
    weight: 12,
    stock: 300,
    minStock: 60,
  },
  {
    name: "Baja Ringan Taso 0.75mm",
    description: "Baja ringan berkualitas untuk rangka atap",
    sku: "BJR-TSO-024",
    price: 45000,
    categorySlug: "besi-baja",
    unit: "batang",
    weight: 4,
    stock: 400,
    minStock: 80,
  },
  {
    name: "Wiremesh M8 150x150mm",
    description: "Wiremesh untuk plat lantai dan dak beton",
    sku: "WRM-M8-025",
    price: 165000,
    categorySlug: "besi-baja",
    unit: "lembar",
    weight: 25,
    stock: 150,
    minStock: 30,
  },

  // Kayu & Plywood (3 products)
  {
    name: "Kayu Meranti Kelas A 4x6x400",
    description: "Kayu meranti berkualitas untuk rangka atap dan kusen",
    sku: "KYU-MRT-026",
    price: 85000,
    categorySlug: "kayu-plywood",
    unit: "batang",
    weight: 15,
    stock: 200,
    minStock: 40,
  },
  {
    name: "Triplek Meranti 122x244x9mm",
    description: "Triplek meranti untuk plafon, partisi, dan furniture",
    sku: "TPK-MRT-027",
    price: 180000,
    categorySlug: "kayu-plywood",
    unit: "lembar",
    weight: 18,
    stock: 120,
    minStock: 25,
  },
  {
    name: "Plywood Albasia 122x244x12mm",
    description: "Plywood albasia untuk kebutuhan furniture dan interior",
    sku: "PLY-ALB-028",
    price: 145000,
    categorySlug: "kayu-plywood",
    unit: "lembar",
    weight: 20,
    stock: 100,
    minStock: 20,
  },

  // Pipa & Fitting (4 products)
  {
    name: "Pipa PVC Rucika 3 inch AW",
    description: "Pipa PVC untuk saluran air bersih dan drainase",
    sku: "PIP-RCK-029",
    price: 85000,
    categorySlug: "pipa-fitting",
    unit: "batang",
    weight: 5,
    stock: 250,
    minStock: 50,
    isFeatured: true,
  },
  {
    name: "Pipa PPR Rucika 1/2 inch PN16",
    description: "Pipa PPR untuk instalasi air panas dan dingin",
    sku: "PIP-PPR-030",
    price: 28000,
    categorySlug: "pipa-fitting",
    unit: "batang",
    weight: 1.5,
    stock: 300,
    minStock: 60,
  },
  {
    name: "Elbow PVC 3 inch 90 Derajat",
    description: "Fitting elbow untuk belokan pipa PVC",
    sku: "FIT-ELB-031",
    price: 12000,
    categorySlug: "pipa-fitting",
    unit: "pcs",
    weight: 0.2,
    stock: 400,
    minStock: 80,
  },
  {
    name: "Knee Drat PVC 3/4 inch",
    description: "Knee drat untuk sambungan pipa dengan ulir",
    sku: "FIT-KNE-032",
    price: 8500,
    categorySlug: "pipa-fitting",
    unit: "pcs",
    weight: 0.15,
    stock: 500,
    minStock: 100,
  },

  // Listrik & Kabel (3 products)
  {
    name: "Kabel NYM Eterna 2x2.5mm",
    description: "Kabel instalasi listrik standar SNI untuk rumah tinggal",
    sku: "KBL-ETR-033",
    price: 285000,
    categorySlug: "listrik-kabel",
    unit: "roll",
    weight: 8,
    stock: 80,
    minStock: 15,
    isFeatured: true,
  },
  {
    name: "Saklar Broco Single Tanam Putih",
    description: "Saklar on/off berkualitas dengan pemasangan tanam",
    sku: "SKL-BRC-034",
    price: 15000,
    categorySlug: "listrik-kabel",
    unit: "pcs",
    weight: 0.1,
    stock: 300,
    minStock: 60,
  },
  {
    name: "Stop Kontak Broco Universal",
    description:
      "Stop kontak dengan lubang universal untuk berbagai jenis colokan",
    sku: "STK-BRC-035",
    price: 18000,
    categorySlug: "listrik-kabel",
    unit: "pcs",
    weight: 0.12,
    stock: 250,
    minStock: 50,
  },

  // Sanitair & Plumbing (3 products)
  {
    name: "Kloset Duduk TOTO CW421J",
    description: "Kloset duduk modern dengan dual flush system",
    sku: "KLS-TOT-036",
    price: 1850000,
    salePrice: 1750000,
    categorySlug: "sanitair-plumbing",
    unit: "set",
    weight: 35,
    stock: 30,
    minStock: 5,
    isFeatured: true,
  },
  {
    name: "Wastafel Toto LW587J + Kran",
    description: "Wastafel keramik dengan desain minimalis modern",
    sku: "WST-TOT-037",
    price: 650000,
    categorySlug: "sanitair-plumbing",
    unit: "set",
    weight: 12,
    stock: 40,
    minStock: 8,
  },
  {
    name: "Shower Set Wasser WS-301S Chrome",
    description: "Shower set lengkap dengan hand shower dan rain shower",
    sku: "SHW-WSR-038",
    price: 385000,
    categorySlug: "sanitair-plumbing",
    unit: "set",
    weight: 3,
    stock: 60,
    minStock: 12,
  },

  // Pintu & Jendela (2 products)
  {
    name: "Pintu Panel Minimalis HPL 80x200",
    description: "Pintu panel modern dengan finishing HPL tahan lama",
    sku: "PNT-PNL-039",
    price: 1250000,
    categorySlug: "pintu-jendela",
    unit: "unit",
    weight: 40,
    stock: 25,
    minStock: 5,
  },
  {
    name: "Jendela Aluminium Sliding 120x120",
    description: "Jendela aluminium sistem sliding dengan kaca 5mm",
    sku: "JND-ALM-040",
    price: 1450000,
    categorySlug: "pintu-jendela",
    unit: "unit",
    weight: 30,
    stock: 20,
    minStock: 4,
  },

  // Atap & Rangka (3 products)
  {
    name: "Genteng Metal Pasir Rainbow Roof",
    description: "Genteng metal berpasir dengan warna tahan lama",
    sku: "GTG-MTL-041",
    price: 85000,
    categorySlug: "atap-rangka",
    unit: "lembar",
    weight: 7,
    stock: 400,
    minStock: 80,
    isFeatured: true,
  },
  {
    name: "Genteng Keramik M-Class Natural",
    description: "Genteng keramik berkualitas tinggi tahan cuaca ekstrim",
    sku: "GTG-KRM-042",
    price: 12000,
    categorySlug: "atap-rangka",
    unit: "pcs",
    weight: 4,
    stock: 2000,
    minStock: 400,
  },
  {
    name: "Asbes Gelombang Duraboard 105x180",
    description: "Asbes fiber untuk atap ekonomis dan tahan lama",
    sku: "ASB-DRB-043",
    price: 45000,
    categorySlug: "atap-rangka",
    unit: "lembar",
    weight: 15,
    stock: 300,
    minStock: 60,
  },

  // Alat Tukang (2 products)
  {
    name: "Palu Stanley STHT51309 16oz",
    description: "Palu baja dengan handle anti slip untuk tukang profesional",
    sku: "PLU-STL-044",
    price: 185000,
    categorySlug: "alat-tukang",
    unit: "pcs",
    weight: 0.8,
    stock: 80,
    minStock: 15,
  },
  {
    name: "Meteran Stanley 5m PowerLock",
    description: "Meteran gulung 5 meter dengan kunci otomatis",
    sku: "MTR-STL-045",
    price: 95000,
    categorySlug: "alat-tukang",
    unit: "pcs",
    weight: 0.3,
    stock: 120,
    minStock: 25,
  },

  // Paku & Baut (2 products)
  {
    name: "Paku Beton 3 inch",
    description: "Paku khusus untuk menembus material beton",
    sku: "PKU-BTN-046",
    price: 35000,
    categorySlug: "paku-baut",
    unit: "kg",
    weight: 1,
    stock: 200,
    minStock: 40,
  },
  {
    name: "Baut Tanam M12x100mm Stainless",
    description: "Baut tanam stainless steel anti karat",
    sku: "BAU-TNM-047",
    price: 85000,
    categorySlug: "paku-baut",
    unit: "box",
    weight: 2,
    stock: 100,
    minStock: 20,
  },

  // Gypsum & Partisi (2 products)
  {
    name: "Gypsum Board Jayaboard 120x240x9mm",
    description: "Gypsum board untuk plafon dan partisi ruangan",
    sku: "GYP-JYB-048",
    price: 45000,
    categorySlug: "gypsum-partisi",
    unit: "lembar",
    weight: 8,
    stock: 300,
    minStock: 60,
  },
  {
    name: "Rangka Hollow Gypsum 4x4",
    description: "Rangka hollow galvanis untuk pemasangan gypsum",
    sku: "RGK-GYP-049",
    price: 28000,
    categorySlug: "gypsum-partisi",
    unit: "batang",
    weight: 3,
    stock: 500,
    minStock: 100,
  },

  // Material Dekoratif (1 product)
  {
    name: "Wallpaper Dinding 3D Modern 45cm x 10m",
    description: "Wallpaper stiker 3D motif modern untuk dekorasi dinding",
    sku: "WLP-3D-050",
    price: 125000,
    salePrice: 110000,
    categorySlug: "material-dekoratif",
    unit: "roll",
    weight: 1,
    stock: 150,
    minStock: 30,
    isFeatured: true,
  },
];

async function seedProducts() {
  console.log("🌱 Seeding products...");

  let seededCount = 0;

  for (const product of products) {
    // Get category by slug
    const category = await prisma.category.findUnique({
      where: { slug: product.categorySlug },
    });

    if (!category) {
      console.log(
        `⚠️ Category not found: ${product.categorySlug} for ${product.name}`
      );
      continue;
    }

    // Generate slug from name
    const slug = product.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");

    // Create or update product
    const createdProduct = await prisma.product.upsert({
      where: { sku: product.sku },
      update: {
        name: product.name,
        slug,
        description: product.description,
        price: product.price,
        salePrice: product.salePrice || null,
        categoryId: category.id,
        unit: product.unit,
        weight: product.weight,
        isFeatured: product.isFeatured || false,
        createdBy: 1, // Default admin user
      },
      create: {
        name: product.name,
        slug,
        description: product.description,
        sku: product.sku,
        price: product.price,
        salePrice: product.salePrice || null,
        categoryId: category.id,
        unit: product.unit,
        weight: product.weight,
        isFeatured: product.isFeatured || false,
        createdBy: 1, // Default admin user
      },
    });

    seededCount++;
  }

  console.log(`✅ ${seededCount} products seeded successfully!`);
}

module.exports = { seedProducts };
